# Dataset Overview

Initial exploratory analysis of our NBA Datasets.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Overview of Games Data From Each Season (2013-2026)

In [10]:
# Example
df = pd.read_parquet("data/raw/games/games_2019-20.parquet")
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SEASON_TYPE
0,22019,1610612740,NOP,New Orleans Pelicans,0021900001,2019-10-22,NOP @ TOR,L,265,43,...,53,30,4,9,19,34,122,-8,1,Regular Season
1,22019,1610612746,LAC,LA Clippers,0021900002,2019-10-22,LAC vs. LAL,W,240,42,...,45,24,8,5,14,25,112,10,1,Regular Season
2,22019,1610612747,LAL,Los Angeles Lakers,0021900002,2019-10-22,LAL @ LAC,L,240,37,...,41,20,4,7,15,24,102,-10,1,Regular Season
3,22019,1610612761,TOR,Toronto Raptors,0021900001,2019-10-22,TOR vs. NOP,W,265,42,...,57,23,7,3,17,24,130,8,1,Regular Season
4,22019,1610612738,BOS,Boston Celtics,0021900008,2019-10-23,BOS @ PHI,L,240,33,...,41,18,4,2,11,29,93,-14,1,Regular Season

In [11]:
# Variable Names
df.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE',
       'SEASON_TYPE'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2284 entries, 0 to 2283
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON_ID          2284 non-null   str
 1   TEAM_ID            2284 non-null   int64
 2   TEAM_ABBREVIATION  2284 non-null   str
 3   TEAM_NAME          2284 non-null   str
 4   GAME_ID            2284 non-null   str
 5   GAME_DATE          2284 non-null   str
 6   MATCHUP            2284 non-null   str
 7   WL                 2284 non-null   str
 8   MIN                2284 non-null   int64
 9   FGM                2284 non-null   int64
 10  FGA                2284 non-null   int64
 11  FG_PCT             2284 non-null   float64
 12  FG3M               2284 non-null   int64
 13  FG3A               2284 non-null   int64
 14  FG3_PCT            2284 non-null   float64
 15  FTM                2284 non-null   int64
 16  FTA                2284 non-null   int64
 17  FT_PCT             2284 non-null   float64
 18  OREB               2284 non-null   int64
 19  DREB               2284 non-null   int64
 20  REB                2284 non-null   int64
 21  AST                2284 non-null   int64
 22  STL                2284 non-null   int64
 23  BLK                2284 non-null   int64
 24  TOV                2284 non-null   int64
 25  PF                 2284 non-null   int64
 26  PTS                2284 non-null   int64
 27  PLUS_MINUS         2284 non-null   int64
 28  VIDEO_AVAILABLE    2284 non-null   int64
 29  SEASON_TYPE        2284 non-null   str
dtypes: float64(3), int64(19), str(8)
memory usage: 687.6 KB

# Overview of Shots Data From Each Season (2013-2026)

In [13]:
# Example
df1 = pd.read_parquet("data/raw/shots/shots_2013-14.parquet")
df1.head()

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,...,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM,SEASON_TYPE
0,Shot Chart Detail,0021300012,2,201143,Al Horford,1610612737,Atlanta Hawks,1,11,35,...,16-24 ft.,19.0,6.0,190.0,1,1,20131030,DAL,ATL,Regular Season
1,Shot Chart Detail,0021300012,4,200794,Paul Millsap,1610612737,Atlanta Hawks,1,11,1,...,Less Than 8 ft.,2.0,-21.0,4.0,1,0,20131030,DAL,ATL,Regular Season
2,Shot Chart Detail,0021300012,8,201143,Al Horford,1610612737,Atlanta Hawks,1,10,27,...,16-24 ft.,17.0,155.0,75.0,1,0,20131030,DAL,ATL,Regular Season
3,Shot Chart Detail,0021300012,11,201143,Al Horford,1610612737,Atlanta Hawks,1,9,55,...,8-16 ft.,9.0,92.0,30.0,1,0,20131030,DAL,ATL,Regular Season
4,Shot Chart Detail,0021300012,19,201143,Al Horford,1610612737,Atlanta Hawks,1,9,26,...,8-16 ft.,15.0,152.0,9.0,1,1,20131030,DAL,ATL,Regular Season

In [20]:
# Variable Names
df1.columns

Index(['GRID_TYPE', 'GAME_ID', 'GAME_EVENT_ID', 'PLAYER_ID', 'PLAYER_NAME',
       'TEAM_ID', 'TEAM_NAME', 'PERIOD', 'MINUTES_REMAINING',
       'SECONDS_REMAINING', 'EVENT_TYPE', 'ACTION_TYPE', 'SHOT_TYPE',
       'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE', 'SHOT_DISTANCE',
       'LOC_X', 'LOC_Y', 'SHOT_ATTEMPTED_FLAG', 'SHOT_MADE_FLAG', 'GAME_DATE',
       'HTM', 'VTM', 'SEASON_TYPE'],
      dtype='str')

In [15]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 218411 entries, 0 to 218410
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   GRID_TYPE            218411 non-null  str
 1   GAME_ID              218411 non-null  str
 2   GAME_EVENT_ID        218411 non-null  int64
 3   PLAYER_ID            218411 non-null  int64
 4   PLAYER_NAME          218411 non-null  str
 5   TEAM_ID              218411 non-null  int64
 6   TEAM_NAME            218411 non-null  str
 7   PERIOD               218411 non-null  int64
 8   MINUTES_REMAINING    218411 non-null  int64
 9   SECONDS_REMAINING    218411 non-null  int64
 10  EVENT_TYPE           218411 non-null  str
 11  ACTION_TYPE          218411 non-null  str
 12  SHOT_TYPE            218411 non-null  str
 13  SHOT_ZONE_BASIC      218362 non-null  str
 14  SHOT_ZONE_AREA       218362 non-null  str
 15  SHOT_ZONE_RANGE      218362 non-null  str
 16  SHOT_DISTANCE        218362 non-null  float64
 17  LOC_X                218362 non-null  float64
 18  LOC_Y                218362 non-null  float64
 19  SHOT_ATTEMPTED_FLAG  218411 non-null  int64
 20  SHOT_MADE_FLAG       218411 non-null  int64
 21  GAME_DATE            218411 non-null  str
 22  HTM                  218411 non-null  str
 23  VTM                  218411 non-null  str
 24  SEASON_TYPE          218411 non-null  str
dtypes: float64(3), int64(8), str(14)
memory usage: 74.5 MB

# Overview of the player data

In [16]:
# Example
df2 = pd.read_parquet("data/raw/players.parquet")
df2.head()

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,TEAM_SLUG,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,alaa_abdelnaby,0,,,,,NaN,Y,00
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,zaid_abdul-aziz,0,,,,,NaN,Y,00
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,kareem_abdul-jabbar,0,,,,,NaN,Y,00
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,mahmoud_abdul-rauf,0,,,,,NaN,Y,00
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,tariq_abdul-wahad,0,,,,,NaN,Y,00

In [18]:
# Variable Names
df2.columns

Index(['PERSON_ID', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FIRST_LAST',
       'ROSTERSTATUS', 'FROM_YEAR', 'TO_YEAR', 'PLAYERCODE', 'PLAYER_SLUG',
       'TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CODE',
       'TEAM_SLUG', 'GAMES_PLAYED_FLAG', 'OTHERLEAGUE_EXPERIENCE_CH'],
      dtype='str')

In [19]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5126 entries, 0 to 5125
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PERSON_ID                  5126 non-null   int64
 1   DISPLAY_LAST_COMMA_FIRST   5126 non-null   str
 2   DISPLAY_FIRST_LAST         5126 non-null   str
 3   ROSTERSTATUS               5126 non-null   int64
 4   FROM_YEAR                  5126 non-null   str
 5   TO_YEAR                    5126 non-null   str
 6   PLAYERCODE                 5126 non-null   str
 7   PLAYER_SLUG                5126 non-null   str
 8   TEAM_ID                    5126 non-null   int64
 9   TEAM_CITY                  5126 non-null   str
 10  TEAM_NAME                  5126 non-null   str
 11  TEAM_ABBREVIATION          5126 non-null   str
 12  TEAM_CODE                  5126 non-null   str
 13  TEAM_SLUG                  530 non-null    str
 14  GAMES_PLAYED_FLAG          5126 non-null   str
 15  OTHERLEAGUE_EXPERIENCE_CH  5126 non-null   str
dtypes: int64(3), str(13)
memory usage: 985.9 KB

# Overview of Teams data

In [21]:
# Example
df3 = pd.read_parquet("data/raw/teams.parquet")
df3.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [22]:
# Variable Names
df2.columns

Index(['PERSON_ID', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FIRST_LAST',
       'ROSTERSTATUS', 'FROM_YEAR', 'TO_YEAR', 'PLAYERCODE', 'PLAYER_SLUG',
       'TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CODE',
       'TEAM_SLUG', 'GAMES_PLAYED_FLAG', 'OTHERLEAGUE_EXPERIENCE_CH'],
      dtype='str')

In [23]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5126 entries, 0 to 5125
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PERSON_ID                  5126 non-null   int64
 1   DISPLAY_LAST_COMMA_FIRST   5126 non-null   str
 2   DISPLAY_FIRST_LAST         5126 non-null   str
 3   ROSTERSTATUS               5126 non-null   int64
 4   FROM_YEAR                  5126 non-null   str
 5   TO_YEAR                    5126 non-null   str
 6   PLAYERCODE                 5126 non-null   str
 7   PLAYER_SLUG                5126 non-null   str
 8   TEAM_ID                    5126 non-null   int64
 9   TEAM_CITY                  5126 non-null   str
 10  TEAM_NAME                  5126 non-null   str
 11  TEAM_ABBREVIATION          5126 non-null   str
 12  TEAM_CODE                  5126 non-null   str
 13  TEAM_SLUG                  530 non-null    str
 14  GAMES_PLAYED_FLAG          5126 non-null   str
 15  OTHERLEAGUE_EXPERIENCE_CH  5126 non-null   str
dtypes: int64(3), str(13)
memory usage: 985.9 KB